// Mock data for Bangladeshi context
export const products = [
  {
    id: 1,
    name: "Ultima Pro Smartwatch",
    price: 12990,
    originalPrice: 15990,
    image: "/futuristic-smartwatch-with-holographic-display.jpg",
    category: "Smart Gear",
    badge: "Flash Sale",
    stock: 5,
  },
  {
    id: 2,
    name: "AeroX TWS Earbuds",
    price: 5490,
    originalPrice: 6990,
    image: "/wireless-earbuds-with-neon-cyan-case.jpg",
    category: "Smart Gear",
    badge: "Bestseller",
    stock: 15,
  },
  {
    id: 3,
    name: "PowerCore 20000mAh",
    price: 2990,
    originalPrice: 3490,
    image: "/sleek-black-power-bank-with-led-display.jpg",
    category: "Daily Utilities",
    badge: null,
    stock: 25,
  },
  {
    id: 4,
    name: "ProTrim Elite Grooming Kit",
    price: 4290,
    originalPrice: 5290,
    image: "/premium-electric-trimmer-grooming-kit.jpg",
    category: "Daily Utilities",
    badge: "New",
    stock: 8,
  },
  {
    id: 5,
    name: "NeonGlow Smart Lamp",
    price: 3490,
    originalPrice: 4290,
    image: "/modern-smart-lamp-with-rgb-lighting.jpg",
    category: "Modern Living",
    badge: null,
    stock: 12,
  },
  {
    id: 6,
    name: "AirPure Mini Purifier",
    price: 8990,
    originalPrice: 10990,
    image: "/minimalist-air-purifier-with-display.jpg",
    category: "Modern Living",
    badge: "Flash Sale",
    stock: 3,
  },
]

export const categories = [
  {
    id: 1,
    name: "Smart Gear",
    image: "/collection-of-smartwatches-and-earbuds-futuristic.jpg",
    description: "Cutting-edge wearables & accessories",
    color: "#00f2ff",
  },
  {
    id: 2,
    name: "Daily Utilities",
    image: "/power-banks-and-grooming-tools-modern.jpg",
    description: "Essential tools for everyday life",
    color: "#8b5cf6",
  },
  {
    id: 3,
    name: "Modern Living",
    image: "/smart-home-devices-lamps-purifiers.jpg",
    description: "Transform your living space",
    color: "#ec4899",
  },
]

export const liveTicker = [
  { user: "Tanvir", location: "Dhaka", product: "AirPods Pro" },
  { user: "Rafiq", location: "Chittagong", product: "Ultima Watch" },
  { user: "Sadia", location: "Sylhet", product: "PowerCore 20K" },
  { user: "Karim", location: "Rajshahi", product: "AeroX Earbuds" },
  { user: "Nadia", location: "Khulna", product: "ProTrim Elite" },
]

export const recentOrders = [
  {
    id: "#RN-2024-001",
    customer: "Tanvir Ahmed",
    email: "tanvir@email.com",
    phone: "+8801712345678",
    address: "House 12, Road 5, Dhanmondi, Dhaka",
    amount: 12990,
    status: "Confirmed",
    date: "2024-01-15",
    invoiceEmailed: true,
    items: [{ name: "Ultima Pro Smartwatch", quantity: 1, price: 12990 }],
  },
  {
    id: "#RN-2024-002",
    customer: "Rafiq Hassan",
    email: "rafiq@email.com",
    phone: "+8801812345678",
    address: "45/B Agrabad, Chittagong",
    amount: 5490,
    status: "Shipped",
    date: "2024-01-15",
    invoiceEmailed: true,
    items: [{ name: "AeroX TWS Earbuds", quantity: 1, price: 5490 }],
  },
  {
    id: "#RN-2024-003",
    customer: "Sadia Rahman",
    email: "sadia@email.com",
    phone: "+8801912345678",
    address: "12 Shahjalal Upashahar, Sylhet",
    amount: 8990,
    status: "Pending",
    date: "2024-01-14",
    invoiceEmailed: false,
    items: [{ name: "AirPure Mini Purifier", quantity: 1, price: 8990 }],
  },
  {
    id: "#RN-2024-004",
    customer: "Karim Uddin",
    email: "karim@email.com",
    phone: "+8801612345678",
    address: "78 Rajshahi Sadar, Rajshahi",
    amount: 2990,
    status: "Confirmed",
    date: "2024-01-14",
    invoiceEmailed: true,
    items: [{ name: "PowerCore 20000mAh", quantity: 1, price: 2990 }],
  },
  {
    id: "#RN-2024-005",
    customer: "Nadia Sultana",
    email: "nadia@email.com",
    phone: "+8801512345678",
    address: "23 Shibbari More, Khulna",
    amount: 4290,
    status: "Shipped",
    date: "2024-01-13",
    invoiceEmailed: true,
    items: [{ name: "ProTrim Elite Grooming Kit", quantity: 1, price: 4290 }],
  },
]

export type Order = (typeof recentOrders)[number]
